sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: qsbSk0oTQJE+fj9sHbZeOCW6mau8I3qmNCFbwRH5krxnlbAdBpW2//jo7891f0he1dAmcaa262oCTjkNYQzFYlotKFCt0OXXsmZSgikG8uhP+6R/COjF0iDs6vxqM9x/P4talzytQeod571pSYza7eKmutaj0rtqvOASxY25TGm+WsdVCE8zZyNftaI7C8krw4ffp8wMBvjZUHMZkpUASKnFGDETuHqLyB4iZ4XZ6eF7KVXMblySu65ACuiilf6Ypwgx0VM2BE3AFuQkG6BUldZhkJXarspnp5UGwdGXVXyC7/Swmps4N32u1cwBwX9TsHskA7tNII1RLxEJoPzIL6TFecef/QdeneESTXcsidqUxrNVBlT23vhHwp8I2/f1PLHQHb5LiLYuETz3Uxidsuaa4IlId74AJ7E8UbhLuuF9hHpldsdxA0LmjqNgYa67OiuX7xRu3P5zdsuC/0Rpk8CFfGL/I04kvv9iMVc/Z9XUrQLQhZFSvh7J+mn6NAruPDB71C+ez2hpb7bNIjG5cKvchwmd9S/3/rTyjA++YfpVkEqSAdQNumaYAI+aTjdDoPShAq8OZBiyp5cJUuBb5n/s2FBqR2FXuz3c1+U+PiOaErYXSiP2Twfuu4WLZXPC1BcMFqZnFRuXOo/vKO5K7/nPBjs7nPXJjGAmHrdGq1E=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Narcissism-Book-of-Quotes--13-A-Selection-of-Quotes-from-the-Collective-Wisdom-of-over-12-000-__4662
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy